id: guest-demo
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: guest-demo
    containers:
      - name: guest-demo
        image: danmcginnis/guest-demo
        cpu: 1000
        ports:
         - name: api
           containerPort: 5000 
           hostPort: 5000
# Fill this value out with the ip of the minion running the rethink container
        env:
         - key: RDB_HOST
           value: 130.211.149.116 
labels:
  name: guest-demo
