id: guestbook
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 3
  replicaSelector:
    name: guestbook
  # This template is basically identical to the single pod
  # definition above
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: guestbook
        containers:
          - name: guestbook
            image: danmcginnis/guest-demo
            cpu: 1000
            ports:
              - name: api
                containerPort: 5000
                hostPort: 5000
            env:
              - key: RDB_HOST
                value: 130.211.149.116
    labels:
      name: guestbook
