id: guest-demo-master
kind: Pod
apiVersion: v1beta1
desiredState:
  manifest:
    version: v1beta1
    id: guest-demo-master
    containers:
      - name: guest-demo
        image: danmcginnis/guest-demo
        cpu: 1000
        ports:
         - name: api
           containerPort: 5000 
           hostPort: 5000
        env:
         - key: RDB_HOST
           value: 146.148.87.245 
labels:
  name: guest-demo
