id: random-number
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 4
  replicaSelector:
  name: random-number
  # This template is basically identical to the single pod
  # definition above
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: random-number
        containers:
          - name: random-number
            image: benraj/webdemo:demo 
            cpu: 100
            ports:
              - name: api
                containerPort: 80
                hostPort: 80
            command:
              - /bin/bash -c 'python lottery/manage.py runserver 0.0.0.0:80'
    labels:
        name: random-number
